### ISSUE TITLE
Build error [Visual Studio]

### ISSUE THREAD

**Issue by amiller911** [ghorsey/OpenGraph-Net#16]
When i try build project i get error: `Users/alex/Downloads/voat-Core/src/external/Source/ghorsey/OpenGraph-Net/CSC: Error CS8102: Public signing was specified and requires a public key, but no public key was specified. (CS8102) (OpenGraph-Net)`

![54372387-cdf23580-46ad-11e9-8233-7bc138d6e76b](https://user-images.githubusercontent.com/42842521/57189011-df7bef00-6f32-11e9-93f7-1cd883ac3726.png)

How to fix its problem?

Thank you.

**Comment by ghorsey** [comment]
Hi @amiller911 

Sorry for the delayed response..  I was on vacay in Portland! 🍻 

Anyway.

It looks like you're trying to build the voat project, which happens to use my component.   

It seems that from the error message that they are using strong-named assemblies.

To understand how to do this checkout:
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/create-and-use-strong-named-assemblies

To use my component in your own project, run the command `dotnet add package OpenGraph-Net --version 3.1.2`.  This way you won't run into any issues with strongly named assemblies.

I'm going to close this issue since there is nothing to change in this repository.
