### ISSUE TITLE
Using OpenGraph-NET on Xamarin.Forms > string.Replace issue?

### ISSUE THREAD

**Issue by sthewissen** [ghorsey/OpenGraph-Net#19]
**Describe the bug**
I was trying to add OpenGraph-NET to my Xamarin.Forms app to do some parsing of OG data. I added the latest NuGet to my cross platform project, which is a .NET Standard 2.0 project. When calling it like so:

`var graph = OpenGraph.ParseUrl(item.ReferenceUrl);`

I get the following error:

![image](https://user-images.githubusercontent.com/2419439/78603145-e6ecfc00-7857-11ea-87e0-d4a50feed12d.png)

I can trace this to the conditional compilation part here: https://github.com/ghorsey/OpenGraph-Net/blob/develop/src/OpenGraphNet/OpenGraph.cs#L361 I have tried to upgrade my project to .NET Standard 2.1, but this did not change the behavior. I also verified that the compiler directive is there. Feels like I'm missing something here, but I'm not quite sure what and was hoping you might know more.

**To Reproduce**
1. Create a blank Xamarin.Forms project.
2. Add the latest NuGet.
3. Try to parse a URL no the first page.

**Expected behavior**
A successfully parsing OpenGraph object.

**Comment by ghorsey** [comment]
@sthewissen  thanks for this report.  strange.  I'll look at this this week and try and get a fix turned around quickly for you.

**Comment by ghorsey** [comment]
Sorry I haven't gotten to this... working on it.

**Comment by ghorsey** [comment]
@sthewissen I don't know what is causing this behavior.  I think this might be a bug with Xamarin forms?

I get your same behavior when I add my library via nuget, but not when I reference the project directly.

I do not get this behavior if I create a netcoreapp2.0 and reference my library via nuget.  

I opened the following issue w/ Xamarin Forms: https://github.com/xamarin/Xamarin.Forms/issues/10458

The workaround I found is this: 

## Workaround
1. Instead of using the nuget package via the package manager, directly add a reference to the netstandard2.0 assembly `%userprofile%\.nuget\packages\opengraph-net\3.2.4\lib\netstandard2.0\OpenGraphNet.dll`
2. Add reference via nuget package manager for HtmlAgilityPack.

**Comment by sthewissen** [comment]
Thanks for taking the effort & investigating further! 

I've done some tests locally with the source downloaded and can confirm it probably goes wrong on a deeper level. Just writing this in my Xamarin app without your library anywhere near it seems to trigger the error.

```
var value = "this is my string";
value = value.Replace("my", "your", StringComparison.InvariantCultureIgnoreCase);
```

**Comment by ghorsey** [comment]
I am going to  close this since it seems to be a framework issue

**Comment by giuseppenovielli** [comment]
@ghorsey 3.2.5 Xamarin.Forms 
Crash!

System.NotImplementedException: The method or operation is not implemented.
